// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using System.Configuration;

[TestFixture]
public class UPSSelenium {
    private IWebDriver driver;
    string TextTdActual = "";
    int PosicionLink = 0;
    string UrlDescarga = "";
    string Urlcompleta = "";

    public IDictionary<string, object> vars {get; private set;}
    private IJavaScriptExecutor js;
    
    [SetUp]
    public void SetUp() {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    
    [TearDown]
    protected void TearDown() {
        driver.Quit();
    }
    
    public string waitForWindow(int timeout) {
        try {
            Thread.Sleep(timeout);
        } catch(Exception e) {
            Console.WriteLine("{0} Exception caught.", e);
        }
        var whNow = ((IReadOnlyCollection<object>)driver.WindowHandles).ToList();
        var whThen = ((IReadOnlyCollection<object>)vars["WindowHandles"]).ToList();
        if (whNow.Count > whThen.Count) {
            return whNow.Except(whThen).First().ToString();
        } else {
            return whNow.First().ToString();
        }
    }


    public void Descarga() 
    {
        string PageSource = driver.PageSource;

        // Obtiene Primer link de descarga
        // -------------------------------
        int PosicionInicial = PageSource.IndexOf("/invoice/showpdf.action?requestor=SCS&amp;filetype=csv");

        if (PosicionInicial > 0)
        {
            TextTdActual = PageSource.Substring(PosicionInicial);
            PosicionLink = TextTdActual.IndexOf(")");
            UrlDescarga = "https://www.apps.ups.com/ebilling/" + TextTdActual.Substring(1, PosicionLink - 2);
            Urlcompleta = UrlDescarga.Replace("amp;", "");

            driver.Navigate().GoToUrl(Urlcompleta);
        }

        System.Threading.Thread.Sleep(5000);
        // Obtiene segundo link de descarga
        // -------------------------------
        PosicionInicial = 0;
        PageSource = TextTdActual.Substring(PosicionLink);
        PosicionInicial = PageSource.IndexOf("/invoice/showpdf.action?requestor=SCS&amp;filetype=csv");
        if (PosicionInicial > 0)
        {
            TextTdActual = PageSource.Substring(PosicionInicial);
            PosicionLink = TextTdActual.IndexOf(")");
            UrlDescarga = "https://www.apps.ups.com/ebilling/" + TextTdActual.Substring(1, PosicionLink - 2);
            Urlcompleta = UrlDescarga.Replace("amp;", "");

            driver.Navigate().GoToUrl(Urlcompleta);
        }

        System.Threading.Thread.Sleep(5000);
        // Obtiene tercero link de descarga
        // -------------------------------
        PosicionInicial = 0;
        PageSource = TextTdActual.Substring(PosicionLink);
        PosicionInicial = PageSource.IndexOf("/invoice/showpdf.action?requestor=SCS&amp;filetype=csv");
        if (PosicionInicial > 0)
        {
            TextTdActual = PageSource.Substring(PosicionInicial);
            PosicionLink = TextTdActual.IndexOf(")");
            UrlDescarga = "https://www.apps.ups.com/ebilling/" + TextTdActual.Substring(1, PosicionLink - 2);
            Urlcompleta = UrlDescarga.Replace("amp;", "");

            driver.Navigate().GoToUrl(Urlcompleta);
        }

        System.Threading.Thread.Sleep(5000);
        // Obtiene cuarto link de descarga
        // -------------------------------
        PosicionInicial = 0;
        PageSource = TextTdActual.Substring(PosicionLink);
        PosicionInicial = PageSource.IndexOf("/invoice/showpdf.action?requestor=SCS&amp;filetype=csv");
        if (PosicionInicial > 0)
        {
            TextTdActual = PageSource.Substring(PosicionInicial);
            PosicionLink = TextTdActual.IndexOf(")");
            UrlDescarga = "https://www.apps.ups.com/ebilling/" + TextTdActual.Substring(1, PosicionLink - 2);
            Urlcompleta = UrlDescarga.Replace("amp;", "");

            driver.Navigate().GoToUrl(Urlcompleta);
        }

        System.Threading.Thread.Sleep(5000);
        // Obtiene quinto link de descarga
        // -------------------------------
        PosicionInicial = 0;
        PageSource = TextTdActual.Substring(PosicionLink);
        PosicionInicial = PageSource.IndexOf("/invoice/showpdf.action?requestor=SCS&amp;filetype=csv");
        if (PosicionInicial > 0)
        {
            TextTdActual = PageSource.Substring(PosicionInicial);
            PosicionLink = TextTdActual.IndexOf(")");
            UrlDescarga = "https://www.apps.ups.com/ebilling/" + TextTdActual.Substring(1, PosicionLink - 2);
            Urlcompleta = UrlDescarga.Replace("amp;", "");

            driver.Navigate().GoToUrl(Urlcompleta);
        }

        System.Threading.Thread.Sleep(5000);
        // Obtiene sexto link de descarga
        // -------------------------------
        PosicionInicial = 0;
        PageSource = TextTdActual.Substring(PosicionLink);
        PosicionInicial = PageSource.IndexOf("/invoice/showpdf.action?requestor=SCS&amp;filetype=csv");
        if (PosicionInicial > 0)
        {
            TextTdActual = PageSource.Substring(PosicionInicial);
            PosicionLink = TextTdActual.IndexOf(")");
            UrlDescarga = "https://www.apps.ups.com/ebilling/" + TextTdActual.Substring(1, PosicionLink - 2);
            Urlcompleta = UrlDescarga.Replace("amp;", "");

            driver.Navigate().GoToUrl(Urlcompleta);
        }

        System.Threading.Thread.Sleep(5000);
        // Obtiene septimo link de descarga
        // -------------------------------
        PosicionInicial = 0;
        PageSource = TextTdActual.Substring(PosicionLink);
        PosicionInicial = PageSource.IndexOf("/invoice/showpdf.action?requestor=SCS&amp;filetype=csv");
        if (PosicionInicial > 0)
        {
            TextTdActual = PageSource.Substring(PosicionInicial);
            PosicionLink = TextTdActual.IndexOf(")");
            UrlDescarga = "https://www.apps.ups.com/ebilling/" + TextTdActual.Substring(1, PosicionLink - 2);
            Urlcompleta = UrlDescarga.Replace("amp;", "");

            driver.Navigate().GoToUrl(Urlcompleta);
        }

        System.Threading.Thread.Sleep(5000);
        // Obtiene octavo link de descarga
        // -------------------------------
        PosicionInicial = 0;
        PageSource = TextTdActual.Substring(PosicionLink);
        PosicionInicial = PageSource.IndexOf("/invoice/showpdf.action?requestor=SCS&amp;filetype=csv");
        if (PosicionInicial > 0)
        {
            TextTdActual = PageSource.Substring(PosicionInicial);
            PosicionLink = TextTdActual.IndexOf(")");
            UrlDescarga = "https://www.apps.ups.com/ebilling/" + TextTdActual.Substring(1, PosicionLink - 2);
            Urlcompleta = UrlDescarga.Replace("amp;", "");

            driver.Navigate().GoToUrl(Urlcompleta);
        }

        System.Threading.Thread.Sleep(5000);
        // Obtiene noveno link de descarga
        // -------------------------------
        PosicionInicial = 0;
        PageSource = TextTdActual.Substring(PosicionLink);
        PosicionInicial = PageSource.IndexOf("/invoice/showpdf.action?requestor=SCS&amp;filetype=csv");
        if (PosicionInicial > 0)
        {
            TextTdActual = PageSource.Substring(PosicionInicial);
            PosicionLink = TextTdActual.IndexOf(")");
            UrlDescarga = "https://www.apps.ups.com/ebilling/" + TextTdActual.Substring(1, PosicionLink - 2);
            Urlcompleta = UrlDescarga.Replace("amp;", "");

            driver.Navigate().GoToUrl(Urlcompleta);
        }

        System.Threading.Thread.Sleep(5000);
        // Obtiene decimo link de descarga
        // -------------------------------
        PosicionInicial = 0;
        PageSource = TextTdActual.Substring(PosicionLink);
        PosicionInicial = PageSource.IndexOf("/invoice/showpdf.action?requestor=SCS&amp;filetype=csv");
        if (PosicionInicial > 0)
        {
            TextTdActual = PageSource.Substring(PosicionInicial);
            PosicionLink = TextTdActual.IndexOf(")");
            UrlDescarga = "https://www.apps.ups.com/ebilling/" + TextTdActual.Substring(1, PosicionLink - 2);
            Urlcompleta = UrlDescarga.Replace("amp;", "");

            driver.Navigate().GoToUrl(Urlcompleta);
        }

        System.Threading.Thread.Sleep(5000);
        // Obtiene onceavo link de descarga
        // -------------------------------
        PosicionInicial = 0;
        PageSource = TextTdActual.Substring(PosicionLink);
        PosicionInicial = PageSource.IndexOf("/invoice/showpdf.action?requestor=SCS&amp;filetype=csv");
        if (PosicionInicial > 0)
        {
            TextTdActual = PageSource.Substring(PosicionInicial);
            PosicionLink = TextTdActual.IndexOf(")");
            UrlDescarga = "https://www.apps.ups.com/ebilling/" + TextTdActual.Substring(1, PosicionLink - 2);
            Urlcompleta = UrlDescarga.Replace("amp;", "");

            driver.Navigate().GoToUrl(Urlcompleta);
        }

        System.Threading.Thread.Sleep(5000);
        // Obtiene doceavo link de descarga
        // -------------------------------
        PosicionInicial = 0;
        PageSource = TextTdActual.Substring(PosicionLink);
        PosicionInicial = PageSource.IndexOf("/invoice/showpdf.action?requestor=SCS&amp;filetype=csv");
        if (PosicionInicial > 0)
        {
            TextTdActual = PageSource.Substring(PosicionInicial);
            PosicionLink = TextTdActual.IndexOf(")");
            UrlDescarga = "https://www.apps.ups.com/ebilling/" + TextTdActual.Substring(1, PosicionLink - 2);
            Urlcompleta = UrlDescarga.Replace("amp;", "");

            driver.Navigate().GoToUrl(Urlcompleta);
        }

        System.Threading.Thread.Sleep(5000);
        // Obtiene treceavo link de descarga
        // -------------------------------
        PosicionInicial = 0;
        PageSource = TextTdActual.Substring(PosicionLink);
        PosicionInicial = PageSource.IndexOf("/invoice/showpdf.action?requestor=SCS&amp;filetype=csv");
        if (PosicionInicial > 0)
        {
            TextTdActual = PageSource.Substring(PosicionInicial);
            PosicionLink = TextTdActual.IndexOf(")");
            UrlDescarga = "https://www.apps.ups.com/ebilling/" + TextTdActual.Substring(1, PosicionLink - 2);
            Urlcompleta = UrlDescarga.Replace("amp;", "");

            driver.Navigate().GoToUrl(Urlcompleta);
        }

        System.Threading.Thread.Sleep(5000);
        // Obtiene catoceavo link de descarga
        // -------------------------------
        PosicionInicial = 0;
        PageSource = TextTdActual.Substring(PosicionLink);
        PosicionInicial = PageSource.IndexOf("/invoice/showpdf.action?requestor=SCS&amp;filetype=csv");
        if (PosicionInicial > 0)
        {
            TextTdActual = PageSource.Substring(PosicionInicial);
            PosicionLink = TextTdActual.IndexOf(")");
            UrlDescarga = "https://www.apps.ups.com/ebilling/" + TextTdActual.Substring(1, PosicionLink - 2);
            Urlcompleta = UrlDescarga.Replace("amp;", "");

            driver.Navigate().GoToUrl(Urlcompleta);
        }

        System.Threading.Thread.Sleep(5000);
        // Obtiene 15 link de descarga
        // -------------------------------
        PosicionInicial = 0;
        PageSource = TextTdActual.Substring(PosicionLink);
        PosicionInicial = PageSource.IndexOf("/invoice/showpdf.action?requestor=SCS&amp;filetype=csv");
        if (PosicionInicial > 0)
        {
            TextTdActual = PageSource.Substring(PosicionInicial);
            PosicionLink = TextTdActual.IndexOf(")");
            UrlDescarga = "https://www.apps.ups.com/ebilling/" + TextTdActual.Substring(1, PosicionLink - 2);
            Urlcompleta = UrlDescarga.Replace("amp;", "");

            driver.Navigate().GoToUrl(Urlcompleta);
        }

    }

  [Test]
  
    public void descargaarchivo() {
        driver.Navigate().GoToUrl("https://www.ups.com/lasso/login");
        driver.Manage().Window.Size = new System.Drawing.Size(1552, 841);
        driver.FindElement(By.LinkText("Log In")).Click();

        System.Threading.Thread.Sleep(5000);
        string Usuario = ConfigurationManager.AppSettings["UsrUPS"];

        driver.FindElement(By.Id("email")).Click();
        driver.FindElement(By.Id("email")).SendKeys(Usuario);

        string PassWord = ConfigurationManager.AppSettings["PassUPS"];

        driver.FindElement(By.Id("pwd")).Click();
        driver.FindElement(By.Id("pwd")).SendKeys(PassWord);
        
        driver.FindElement(By.Id("submitBtn")).Click();
       

        try
        {
            driver.FindElement(By.LinkText("View & Pay Bill")).Click();
        }
        catch (NoSuchElementException e)
        {
            driver.FindElement(By.Id("ups-quickStartMenu")).Click();
            driver.FindElement(By.LinkText("View & Pay Bill")).Click();
        }
        catch (StaleElementReferenceException e)
        {
            Console.WriteLine(e.Message);
        }
        catch (WebDriverException e)
        {
            Console.WriteLine(e.Message);
        }

        driver.FindElement(By.CssSelector(".ups-list:nth-child(1) .ups-list_link:nth-child(1) h3")).Click();
        
        System.Threading.Thread.Sleep(5000);

        driver.FindElement(By.Id("onetimePay_businessUnitupsSCS")).Click();

        System.Threading.Thread.Sleep(5000);
        driver.FindElement(By.LinkText("View Your Invoice")).Click();

        driver.FindElement(By.CssSelector("table:nth-child(2) td:nth-child(5) > input")).Click();
        driver.FindElement(By.Id("fromShipmentDate")).Clear();

        string DiasRango = ConfigurationManager.AppSettings["DiasFacturacion"];

        int DiasRetroceder = Convert.ToInt32(DiasRango);
        DiasRetroceder = DiasRetroceder * -1;

        string varFechaInicio = DateTime.Today.AddDays(DiasRetroceder).ToString("MM/dd/yyyy");

        driver.FindElement(By.Id("fromShipmentDate")).Clear();
        driver.FindElement(By.Id("fromShipmentDate")).SendKeys(varFechaInicio);

        driver.FindElement(By.Name("invoiceStatus")).SendKeys("A");

        driver.FindElement(By.CssSelector(".bSwanR")).Click();

        System.Threading.Thread.Sleep(5000);


        try
        {
            Descarga();
        }
        catch (SystemException e)
        {
            Console.WriteLine(e.Message);
        }
        catch (NoSuchElementException e)
        {
            Console.WriteLine(e.Message);
            Console.WriteLine("Fin Descarga");
        }
        catch (StaleElementReferenceException e)
        {
            Console.WriteLine(e.Message);
        }
        catch (WebDriverException e)
        {
            Console.WriteLine(e.Message);
        }

        driver.Navigate().GoToUrl("https://www.apps.ups.com/ebilling/invoice/scsCoSummarySearch.action?reportId=scsCoSumm&status=initial");
        driver.FindElement(By.LinkText("Home")).Click();
        driver.FindElement(By.Id("onetimePay_businessUnitupsFreight")).Click();
        System.Threading.Thread.Sleep(5000);
        driver.FindElement(By.LinkText("View Your Invoice")).Click();
        
        try
        {
            Descarga();
        }
        catch (SystemException e)
        {
            Console.WriteLine(e.Message);
        }
        catch (NoSuchElementException e)
        {
            Console.WriteLine(e.Message);
            Console.WriteLine("Fin Descarga");
        }
        catch (StaleElementReferenceException e)
        {
            Console.WriteLine(e.Message);
        }
        catch (WebDriverException e)
        {
            Console.WriteLine(e.Message);
        }

        driver.Navigate().GoToUrl("https://www.apps.ups.com/ebilling/invoice/scsCoSummarySearch.action?reportId=scsCoSumm&status=initial");
        driver.FindElement(By.LinkText("Home")).Click();
        driver.FindElement(By.Id("onetimePay_businessUnitupsPackage")).Click();
        System.Threading.Thread.Sleep(5000);
        driver.FindElement(By.LinkText("View Your Invoice")).Click();

        try
        {
            Descarga();
        }
        catch (SystemException e)
        {
            Console.WriteLine(e.Message);
        }
        catch (NoSuchElementException e)
        {
            Console.WriteLine(e.Message);
            Console.WriteLine("Fin Descarga");
        }
        catch (StaleElementReferenceException e)
        {
            Console.WriteLine(e.Message);
        }
        catch (WebDriverException e)
        {
            Console.WriteLine(e.Message);
        }

        // cierra sesion         
        driver.Navigate().GoToUrl("https://www.apps.ups.com/ebilling/sso/logout.action");

        driver.Close();
  }
}
